"""empty message

Revision ID: 13b4099865b8
Revises: 30b06c947928
Create Date: 2021-05-31 23:22:40.045471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b4099865b8'
down_revision = '30b06c947928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_name_key', 'items', type_='unique')
    op.create_unique_constraint(op.f('uq_items_name'), 'items', ['name'])
    op.drop_constraint('stores_name_key', 'stores', type_='unique')
    op.create_unique_constraint(op.f('uq_stores_name'), 'stores', ['name'])
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint(op.f('uq_stores_name'), 'stores', type_='unique')
    op.create_unique_constraint('stores_name_key', 'stores', ['name'])
    op.drop_constraint(op.f('uq_items_name'), 'items', type_='unique')
    op.create_unique_constraint('items_name_key', 'items', ['name'])
    # ### end Alembic commands ###
